"""Initial migration

Revision ID: 358516963cdb
Revises: 
Create Date: 2026-04-03 15:05:44.265642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358516963cdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actresses', schema=None) as batch_op:
        batch_op.alter_column('popularity_score',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
        batch_op.create_index(batch_op.f('ix_actresses_popularity_score'), ['popularity_score'], unique=False)
        batch_op.drop_column('javdb_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('javdb_code', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_actresses_popularity_score'))
        batch_op.alter_column('popularity_score',
                   existing_type=sa.Float(),
                   type_=sa.REAL(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(0.0)'))
    # ### end Alembic commands ###
